"""empty message

Revision ID: 2f5fc91814df
Revises: 6d0ec5351206
Create Date: 2021-09-03 21:07:14.567774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f5fc91814df'
down_revision = '6d0ec5351206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('ability', sa.String(length=50), nullable=True))
    op.add_column('pokemon', sa.Column('experience', sa.String(length=50), nullable=True))
    op.add_column('pokemon', sa.Column('image', sa.String(length=200), nullable=True))
    op.add_column('pokemon', sa.Column('sprite_url', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pokemon', 'sprite_url')
    op.drop_column('pokemon', 'image')
    op.drop_column('pokemon', 'experience')
    op.drop_column('pokemon', 'ability')
    # ### end Alembic commands ###
