"""empty message

Revision ID: f3b735d802f0
Revises: 2f5fc91814df
Create Date: 2021-09-03 21:45:03.340172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3b735d802f0'
down_revision = '2f5fc91814df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('image_url', sa.String(length=200), nullable=True))
    op.drop_column('pokemon', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('image', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('pokemon', 'image_url')
    # ### end Alembic commands ###
